export default [
  { name: 'AAP isolved', id: 'aap_isolved' },
  { name: 'Abacus HCM isolved', id: 'abacus_isolved' },
  { name: 'Absolute Payroll isolved', id: 'absolute_isolved' },
  { name: 'Accupay isolved', id: 'accupay_isolved' },
  { name: 'Ace Workforce Technologies isolved', id: 'ace_isolved' },
  { name: 'ADP TotalSource', id: 'adp_totalsource' },
  { name: 'ADP Workforce Now', id: 'adp_workforce_now' },
  {
    name: 'Advantage Payroll Services',
    id: 'advantage_payroll_services',
  },
  {
    name: 'Affiliated HR Payroll Services is',
    id: 'affiliated_hr_payroll_services_isolved',
  },
  {
    name: 'Affiliated HR Payroll Services Ev',
    id: 'affiliated_hr_payroll_services_evolution',
  },
  { name: 'Ahola', id: 'ahola' },
  { name: 'AlphaStaff', id: 'alphastaff' },
  { name: 'Amplify HR', id: 'amplify_hr' },
  { name: 'APS Payroll', id: 'aps_payroll' },
  { name: 'Asset HR', id: 'asset_hr' },
  { name: 'Asure Software', id: 'asure_software' },
  { name: 'Balance Point', id: 'balance_point' },
  { name: 'Bamboo HR', id: 'bamboo_hr' },
  { name: 'Baron Payroll isolved', id: 'baron_isolved' },
  { name: 'BBCS Payroll', id: 'bbcs' },
  {
    name: 'Big Fish Employer Services',
    id: 'big_fish_employer_services',
  },
  { name: 'Bene-Care', id: 'benecare' },
  { name: 'Bizchecks Payroll', id: 'bizchecks_payroll' },
  { name: 'bob', id: 'bob' },
  { name: 'Ceridian Dayforce', id: 'ceridian_dayforce' },
  { name: 'Ceridian Powerpay', id: 'ceridian_powerpay' },
  { name: 'CharlieHR', id: 'charlie_hr' },
  { name: 'Collage', id: 'collage' },
  { name: 'CoAdvantage', id: 'coadvantage' },
  { name: 'Coastal Payroll', id: 'coastal_payroll' },
  { name: 'Cognos HR', id: 'cognos_hr' },
  {
    name: 'Commonwealth Payroll & HR',
    id: 'commonwealth_payroll_hr',
  },
  { name: 'CPM Employer Services isolved', id: 'cpm_isolved' },
  {
    name: 'Crescent Payroll Solutions',
    id: 'crescent_payroll_solutions',
  },
  { name: 'Deel', id: 'deel' },
  { name: 'Dominion Payroll', id: 'dominion_payroll' },
  { name: 'Employdrive', id: 'employdrive' },
  { name: 'EmPower HR', id: 'empower_hr' },
  { name: 'Finch', id: 'finch' },
  { name: 'Goco', id: 'goco' },
  { name: 'Gusto', id: 'gusto' },
  {
    name: 'GTM Payroll Services isolved',
    id: 'gtm_payroll_services_isolved',
  },
  {
    name: 'GTM Payroll Services Evolution',
    id: 'gtm_payroll_services_evolution',
  },
  { name: 'Highflyer HR', id: 'highflyer_hr' },
  { name: 'Hubstaff', id: 'hubstaff' },
  { name: 'Humi', id: 'humi' },
  { name: 'Insperity', id: 'insperity' },
  { name: 'isolve', id: 'isolved' },
  { name: 'Justworks', id: 'justworks' },
  { name: 'Keystone Payroll isolved', id: 'keystone_isolved' },
  { name: 'mp', id: 'mp' },
  { name: 'Namely', id: 'namely' },
  { name: 'NaturalHR', id: 'natural_hr' },
  { name: 'Nextep', id: 'nextep' },
  { name: 'Newtek', id: 'newtek' },
  { name: 'OneSource Payroll', id: 'onesource_payroll' },
  { name: 'OnPay', id: 'onpay' },
  { name: 'Oracle PeopleSoft', id: 'oracle_peoplesoft' },
  { name: 'Paragon Payroll isolved', id: 'paragon_payroll_isolved' },
  { name: 'Patriot', id: 'patriot' },
  { name: 'PayFit', id: 'payfit' },
  { name: 'PayNorthwest', id: 'paynw' },
  { name: 'PayUSA', id: 'pay_usa_inc' },
  { name: 'Paychex Flex', id: 'paychex_flex' },
  { name: 'Paycor', id: 'paycor' },
  { name: 'Paycom', id: 'paycom' },
  {
    name: 'Payday Workforce Solutions',
    id: 'payday_workforce_solutions',
  },
  { name: 'Paylocity', id: 'paylocity' },
  { name: 'PayPro HCS isolved', id: 'paypro_hcs_isolved' },
  { name: 'Payroll Network', id: 'payroll_network' },
  {
    name: 'Payroll Office of America',
    id: 'payroll_office_of_america',
  },
  {
    name: 'Payroll Plus HCM isolved',
    id: 'payroll_plus_hcm_isolved',
  },
  {
    name: 'Payroll Plus HCM Evolution',
    id: 'payroll_plus_hcm_evolution',
  },
  { name: 'Payroll Solutions', id: 'payroll_solutions' },
  { name: 'PCS HCM', id: 'pcs_hcm' },
  { name: 'Platinum Group', id: 'platinum_group' },
  { name: 'PrimePay', id: 'primepay' },
  { name: 'PrismHR', id: 'prism_hr' },
  { name: 'Proliant', id: 'proliant' },
  { name: 'Proxus HR isolved', id: 'proxus_hr' },
  { name: 'Quickbooks Payroll', id: 'quickbooks' },
  { name: 'Remote', id: 'remote' },
  { name: 'Run Powered by ADP', id: 'adp_run' },
  {
    name: 'Sage 50 US Edition Accounting',
    id: 'sage_50_us_edition_accounting',
  },
  {
    name: 'Sage 50 Quantum Accounting',
    id: 'sage_50_quantum_accounting',
  },
  { name: 'Sage Payroll', id: 'sage_payroll' },
  { name: 'Sapling', id: 'sapling' },
  { name: 'Savant HCM Evolution', id: 'savant_hcm_evolution' },
  { name: 'Sequoia One', id: 'sequoia_one' },
  { name: 'Square Payroll', id: 'square_payroll' },
  { name: 'SAP SuccessFactors', id: 'successfactors' },
  { name: 'SuitePeople (Oracle NetSuite)', id: 'suite_people' },
  {
    name: 'Strategic Payroll Solutions isolv',
    id: 'strategic_payroll_solutions_isolved',
  },
  { name: 'SyncHR', id: 'sync_hr' },
  { name: 'The Payroll Company', id: 'the_payroll_company' },
  { name: 'Toast Payroll', id: 'toast_payroll' },
  { name: 'TriNet', id: 'trinet' },
  { name: 'UKG Ready (Kronos)', id: 'ukg_ready' },
  { name: 'UltiPro', id: 'ulti_pro' },
  { name: 'VensureHR', id: 'vensure_hr' },
  {
    name: 'Viewpoint HR Management Spectrum',
    id: 'viewpoint_hr_management_spectrum',
  },
  {
    name: 'Viewpoint HR Management Vista',
    id: 'viewpoint_hr_management_vista',
  },
  { name: 'Wagepoint', id: 'wagepoint' },
  { name: 'Wave Payroll', id: 'wave' },
  { name: 'WebHR', id: 'web_hr' },
  { name: 'whirks', id: 'whirks' },
  { name: 'Workday', id: 'workday' },
  { name: 'wurk', id: 'wurk' },
  { name: 'Xero', id: 'xero' },
  { name: 'Zenefits', id: 'zenefits' },
  { name: 'Zoho Payroll', id: 'zoho_payroll' },
  { name: 'Other', id: 'other' },
];
